### ISSUE TITLE
WORDPLATE/Acf abandonned

### ISSUE THREAD

**Issue by claireywd** [yeswedev-team/ywd-acf-field-group#1]
Il semble que [ Wordplate/acf](https://packagist.org/packages/wordplate/acf) soit abandonné au profit de [ vinkla/extended-acf](https://github.com/vinkla/extended-acf).

Il faudrait maj les dépendances

**Comment by Nyobec** [comment]
Le plugin n'a pas wordplate/extended-acf en dépendance.
Cette dépendance est dans le composer.json à la racine des projet WP (Bedrock).
